Repository lsst-epo/rubin-obs-api, pull requests merged in 2024-07, with the labels that each got.

#258 Updated Craft to `v4.10.2`
  api/composer.json
  api/composer.lock
  api/plugins/nextbuilds/CHANGELOG.md
  api/plugins/nextbuilds/composer.json
  api/plugins/nextbuilds/src/NextBuilds.php
  api/plugins/nextbuilds/src/services/Request.php
Labels: july-11-2024-release

#275 Correctly traversing Structures event object
  api/plugins/nextbuilds/CHANGELOG.md
  api/plugins/nextbuilds/composer.json
  api/plugins/nextbuilds/src/NextBuilds.php
Labels: july-25-2024-release

#276 chore(DAM): update Canto plugin
  api/composer.json
  api/composer.lock
Labels: bug, dependencies, july-25-2024-release
